### PR TITLE
Output unified diff on failures

### PR DESCRIPTION
**Pull request by zidel**

### CODE REVIEW

**Comment by crondaemon** [comment]
Hi. I am sorry you made all this effort on this project that has been basically left behind. The Wireshark test suite is now part of the main source code tree. Indeed it would be better we delete this project, otherwise people will keep to make PRs. We would be glad to accept your testcases through the official Wireshark merge requests on Gitlab. Sorry for the noise.

/cc @geraldcombs @Lekensteyn

**Comment by zidel** [comment]
I brought this up during the last developer den, and the suggestion was that I submit my test cases here in an attempt to revive this repo as the main repo testsuite was the wrong place due to CI runtime concerns. Gerald might be able to expand on the word needed I guess.

**Comment by crondaemon** [comment]
Glad to hear that. I am looking forward to know how it ends up.

**Comment by geraldcombs** [comment]
We should probably get input from the general developer community on this, so I've started a discussion on -dev: https://www.wireshark.org/lists/wireshark-dev/202101/msg00052.html

**Pull request closed without merging**
